export const metadata = {
  title: "SR Shop",
  description: "Generated by Skynet",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body> {children}</body>
    </html>
  );
}
